# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_gamemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemap',
            name='high_score',
            field=models.IntegerField(default=120),
        ),
    ]
