# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_gamemap_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemap',
            name='input_img',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pics/'),
        ),
    ]
