# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_gamemap_input_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemap',
            name='input_img',
            field=models.ImageField(default='pics/no-img.jpg', upload_to='pics/'),
        ),
    ]
