# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_auto_20170529_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemap',
            name='high_score_name',
            field=models.CharField(default='Anonymous', max_length=20),
        ),
    ]
